apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage-nginx-statefulset
  namespace: namespace-one
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
