apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: namespace-one
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      server {
        listen 80;
        
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
        
        # Metrics endpoint for Prometheus
        location /metrics {
          stub_status on;
          allow 127.0.0.1; # Allow access from localhost
          deny all; # Deny access from others
        }
      }
    }
